### ISSUE TITLE
can't find index.php

### ISSUE THREAD

**Issue by ivanoats** [topfunky/PeepOpen-Issues#196]
Editing a Joomla project (I know, I know I still have to deal with PHP, I can't be a ruby snob all day long) I pressed command-T and typed index but it didn't find index.php in the root of the project. Same for README etc..

**Comment by topfunky** [comment]
We're releasing a bugfix version within the next few days that should fix this and other root directory or missing file issues.

**Comment by jwhitley** [comment]
I'm seeing a missing file issue under TextMate invoked via "mate ." inside of a homebrew root directory.  Typing `Cmd-T e m a c s` brings up only Formulas/uemacs.rb in the list; Formulas/emacs.rb doesn't appear at all even though it exists on disk and is visible in TextMate's project view.

Versions:
1. PeepOpen v0.3.2
2. TextMate 1.5.10 (1631)
3. Mac OS X 10.6.7

**Comment by topfunky** [comment]
@jwhitley I wasn't able to reproduce the error. Setting PeepOpen's preferences to look for All files, it indexed about 18,000 files and showed both emacs.rb and uemacs.rb. Are your preferences set to "All"?

**Comment by topfunky** [comment]
@ivanoats Are you still experiencing this problem? The 0.3.2 release should have fixed root directory issues.

**Comment by ivanoats** [comment]
I've been back to rails projects so haven't noticed but I just did a test on a wordpress project and it works finding Rakefile, index.php and wp-config.php.  In a Joomla project it still won't find configuration.php or Rakefile

**Comment by jwhitley** [comment]
@topfunky  Arrgh.  This no longer repros for me, either.  I'll note that I'd uninstalled the TextMate plugin then reinstalled it between my original investigation and this repro due to the problem I was seeing.

**Comment by jwhitley** [comment]
I'm seeing this again with PeepOpen under TextMate, with TextMate project-opened to the root of the current Emacs bzr repository HEAD.  Entire top-level directories aren't even showing up (e.g. lisp/).  PeepOpen shows "1078 records" but a rough count via `find -type f | grep -v '\.elc$\|\.o$' | wc -l` shows 3574 files.
